-- Run this in your Supabase SQL Editor

-- 1. Create the table
create table vouches (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  text text not null,
  image_url text not null,
  rotation numeric default 0
);

-- 2. Enable RLS (Row Level Security)
alter table vouches enable row level security;

-- 3. Create Policy: Allow Public Read access
create policy "Public Vouches are viewable by everyone"
  on vouches for select
  using ( true );

-- 4. Create Policy: Allow Public Insert access (Guestbook style)
create policy "Anyone can insert a vouch"
  on vouches for insert
  with check ( true );

-- 5. Create Storage Bucket for images
insert into storage.buckets (id, name, public)
values ('vouches', 'vouches', true);

-- 6. Storage Policy: Allow Public Read
create policy "Give public access to vouch images"
  on storage.objects for select
  using ( bucket_id = 'vouches' );

-- 7. Storage Policy: Allow Public Upload
create policy "Give public access to upload vouch images"
  on storage.objects for insert
  with check ( bucket_id = 'vouches' );
